// Base de dados completa de interpretações numerológicas extraídas das fontes
// Baseado em: Livro Numerologia Pitagórica, O Significado dos Números Cabalísticos, 
// Sinastria Numerológica e outras fontes fornecidas

const interpretacoesPitagoricasCompletas = {
  motivacao: {
    1: {
      titulo: "Motivação 1 - O Impulso Primordial da Individualidade",
      texto: "Sua motivação mais profunda nasce do impulso primordial de afirmar sua individualidade única no mundo, como uma força criativa que busca constantemente expressar sua originalidade através de ações pioneiras e iniciativas inovadoras. Esta energia motivacional o impulsiona a ser o primeiro, o líder, o iniciador de novos caminhos, não por vaidade ou competição, mas por uma necessidade visceral de manifestar sua essência única. Você é motivado pela necessidade de criar algo que nunca existiu antes, de abrir portas que outros nem sabiam que existiam, e de demonstrar que é possível transcender limitações através da força de vontade pura e da coragem de ser autêntico. Esta motivação o leva a buscar constantemente situações onde possa exercer liderança natural, tomar decisões independentes e influenciar o curso dos eventos através de sua visão pessoal. Sua alma se alimenta da energia da criação, da inovação e da possibilidade constante de reinventar-se e reinventar o mundo ao seu redor. Na tradição cabalística, o número 1 representa o pai dos números, a harmonia primordial, a iniciação aos mistérios superiores e o autodomínio sobre as forças menores. É o símbolo do prestidigitador, do homem Adão em sua pureza original, de Osíris em sua majestade divina e de Apolo em sua luminosidade solar."
    },
    2: {
      titulo: "Motivação 2 - A Busca Sagrada pela Harmonia Universal",
      texto: "Sua motivação mais profunda emerge da busca sagrada pela harmonia universal e pela criação de pontes de compreensão entre mundos aparentemente opostos. Você é impulsionado por uma necessidade visceral de criar paz, equilíbrio e cooperação onde antes havia conflito, divisão ou incompreensão. Esta energia motivacional o leva a buscar constantemente oportunidades de mediar, harmonizar e unir pessoas, ideias ou situações que parecem irreconciliáveis. Sua alma se nutre da energia da diplomacia, da sensibilidade emocional refinada e da capacidade de perceber as necessidades não expressas dos outros. Você é motivado pela visão de um mundo onde diferenças são celebradas como complementaridades, onde conflitos são transformados em oportunidades de crescimento mútuo, e onde cada ser humano se sente verdadeiramente compreendido e valorizado. Esta motivação o impulsiona a desenvolver uma inteligência emocional extraordinária e uma capacidade natural de criar ambientes onde outros se sentem seguros para serem vulneráveis e autênticos. Na tradição cabalística, o número 2 representa o intelecto superior e a fonte da concepção mental refinada. É o número das pessoas naturalmente receptivas e passivas, que mostram-se calmas, gentis, bondosas, organizadas e escrupulosas em seus relacionamentos e compromissos."
    },
    3: {
      titulo: "Motivação 3 - A Expressão Criativa da Alegria Divina",
      texto: "Sua motivação mais profunda brota da necessidade irreprimível de expressar a alegria divina através de todas as formas de criatividade, comunicação e manifestação artística. Você é impulsionado por uma força vital que busca constantemente transformar experiências internas em expressões externas belas, inspiradoras e comunicativas. Esta energia motivacional o leva a buscar meios de compartilhar sua visão única do mundo através da palavra falada, da arte, da música, da escrita ou de qualquer forma de expressão que permita que sua luz interior brilhe e toque a vida de outros. Sua alma se alimenta da energia da criação artística, da comunicação autêntica e da capacidade de inspirar alegria e otimismo nos outros. Você é motivado pela visão de um mundo onde a beleza, a criatividade e a expressão genuína são valorizadas como forças transformadoras capazes de elevar a consciência humana. Esta motivação o impulsiona a desenvolver talentos comunicativos excepcionais e uma capacidade natural de ver possibilidades onde outros veem limitações. Sua presença naturalmente eleva o ânimo dos ambientes e das pessoas, pois você carrega dentro de si a chama sagrada da inspiração criativa que busca constantemente novas formas de se manifestar no mundo."
    },
    4: {
      titulo: "Motivação 4 - A Construção Sagrada de Fundações Eternas",
      texto: "Sua motivação mais profunda emerge da necessidade fundamental de construir bases sólidas, duradouras e confiáveis que possam sustentar não apenas sua própria vida, mas também servir como fundação para que outros possam construir seus sonhos e aspirações. Você é impulsionado por uma força organizadora que busca constantemente criar ordem, estrutura e estabilidade em um mundo frequentemente caótico e imprevisível. Esta energia motivacional o leva a buscar formas de estabelecer sistemas, processos e estruturas que funcionem de maneira eficiente e confiável ao longo do tempo. Sua alma se alimenta da energia da construção metódica, do trabalho árduo bem executado e da satisfação de ver projetos crescerem desde a concepção até a realização completa. Você é motivado pela visão de um mundo onde a segurança, a estabilidade e a confiabilidade são valorizadas como pilares fundamentais de uma sociedade próspera e harmoniosa. Esta motivação o impulsiona a desenvolver uma disciplina excepcional e uma capacidade natural de transformar ideias abstratas em realidades concretas e tangíveis. Sua presença traz uma sensação de segurança e confiança aos ambientes, pois você representa a força estabilizadora que permite que outros se sintam seguros para sonhar e criar."
    },
    5: {
      titulo: "Motivação 5 - A Busca Infinita pela Liberdade e Experiência",
      texto: "Sua motivação mais profunda nasce da necessidade irreprimível de experimentar a liberdade em todas as suas formas e de explorar as infinitas possibilidades que a vida oferece. Você é impulsionado por uma força expansiva que busca constantemente novas experiências, novos horizontes e novas formas de compreender e interagir com o mundo. Esta energia motivacional o leva a buscar aventuras, mudanças e oportunidades de crescimento que ampliem sua perspectiva e enriqueçam sua compreensão da existência. Sua alma se alimenta da energia da descoberta, da aventura e da capacidade de adaptar-se rapidamente a novas circunstâncias e desafios. Você é motivado pela visão de um mundo onde a diversidade, a mudança e a exploração são valorizadas como forças essenciais para o crescimento e a evolução humana. Esta motivação o impulsiona a desenvolver uma versatilidade excepcional e uma capacidade natural de encontrar oportunidades onde outros veem apenas obstáculos. Sua presença traz dinamismo e energia renovadora aos ambientes, pois você carrega dentro de si o espírito do explorador que está sempre pronto para a próxima aventura ou descoberta."
    },
    6: {
      titulo: "Motivação 6 - O Serviço Amoroso à Harmonia e ao Cuidado",
      texto: "Sua motivação mais profunda emerge da necessidade fundamental de nutrir, cuidar e servir ao bem-estar de outros, criando ambientes de harmonia, beleza e amor incondicional. Você é impulsionado por uma força compassiva que busca constantemente formas de aliviar o sofrimento, promover a cura e estabelecer relações baseadas no cuidado mútuo e na responsabilidade compartilhada. Esta energia motivacional o leva a buscar oportunidades de servir à família, à comunidade e à humanidade através de atos de amor, compreensão e dedicação desinteressada. Sua alma se alimenta da energia do serviço amoroso, da criação de beleza e da capacidade de transformar ambientes através do cuidado atencioso e da presença compassiva. Você é motivado pela visão de um mundo onde o amor, a responsabilidade e o cuidado mútuo são valorizados como as forças mais poderosas para a transformação e a cura. Esta motivação o impulsiona a desenvolver uma capacidade excepcional de compreender as necessidades emocionais dos outros e uma habilidade natural de criar espaços onde todos se sentem amados, valorizados e cuidados."
    },
    7: {
      titulo: "Motivação 7 - A Busca Mística pela Verdade Interior",
      texto: "Sua motivação mais profunda nasce da necessidade irreprimível de compreender os mistérios mais profundos da existência e de descobrir as verdades universais que governam a vida e o cosmos. Você é impulsionado por uma força investigativa que busca constantemente penetrar além das aparências superficiais para alcançar a essência espiritual e filosófica de todas as coisas. Esta energia motivacional o leva a buscar conhecimento através da introspecção, da meditação, do estudo profundo e da análise cuidadosa dos padrões que conectam todas as manifestações da vida. Sua alma se alimenta da energia da descoberta espiritual, da contemplação silenciosa e da capacidade de perceber conexões sutis que escapam à percepção comum. Você é motivado pela visão de um mundo onde a sabedoria, a intuição e a compreensão espiritual são valorizadas como guias essenciais para a evolução da consciência humana. Esta motivação o impulsiona a desenvolver uma percepção excepcional dos aspectos ocultos da realidade e uma capacidade natural de servir como ponte entre o mundo material e as dimensões mais sutis da existência."
    },
    8: {
      titulo: "Motivação 8 - A Manifestação do Poder Material e Espiritual",
      texto: "Sua motivação mais profunda emerge da necessidade fundamental de manifestar poder, autoridade e influência de forma a criar transformações significativas no mundo material e espiritual. Você é impulsionado por uma força organizadora que busca constantemente construir impérios, estabelecer legados duradouros e exercer liderança em grande escala. Esta energia motivacional o leva a buscar posições de responsabilidade e autoridade onde possa implementar visões ambiciosas e criar mudanças que impactem positivamente a vida de muitas pessoas. Sua alma se alimenta da energia da realização material, do sucesso conquistado através do esforço próprio e da capacidade de transformar recursos em resultados tangíveis e mensuráveis. Você é motivado pela visão de um mundo onde o poder é exercido com sabedoria e responsabilidade, onde o sucesso material serve como meio para promover o bem-estar coletivo e onde a autoridade é usada para proteger e elevar aqueles que estão sob sua influência. Esta motivação o impulsiona a desenvolver uma capacidade excepcional de organizar recursos e pessoas em direção a objetivos ambiciosos e uma habilidade natural de inspirar confiança e respeito através de suas realizações concretas."
    },
    9: {
      titulo: "Motivação 9 - A Compaixão Universal e o Serviço à Humanidade",
      texto: "Sua motivação mais profunda nasce da necessidade irreprimível de servir à evolução da consciência humana através da compaixão universal, da sabedoria espiritual e do amor incondicional por toda a criação. Você é impulsionado por uma força transcendente que busca constantemente formas de aliviar o sofrimento mundial, promover a compreensão entre os povos e contribuir para a elevação espiritual da humanidade. Esta energia motivacional o leva a buscar oportunidades de servir causas maiores que transcendem interesses pessoais, dedicando sua vida ao bem-estar coletivo e à promoção da paz, da justiça e da harmonia universal. Sua alma se alimenta da energia do amor universal, da sabedoria compassiva e da capacidade de ver a unidade subjacente que conecta todos os seres. Você é motivado pela visão de um mundo onde a compaixão, a sabedoria e o amor incondicional são reconhecidos como as forças mais poderosas para a transformação e a cura planetária. Esta motivação o impulsiona a desenvolver uma compreensão excepcional da natureza humana e uma capacidade natural de inspirar outros a transcenderem suas limitações pessoais em favor do bem maior."
    }
  },
  
  impressao: {
    1: {
      titulo: "Impressão 1 - A Presença Magnética do Líder Natural",
      texto: "Você projeta naturalmente uma presença magnética de liderança que faz com que outros instintivamente o vejam como alguém capaz de tomar decisões importantes e liderar em situações desafiadoras. Sua energia externa comunica confiança, determinação e uma capacidade inata de assumir responsabilidades que outros hesitariam em aceitar. Pessoas ao seu redor percebem em você uma força motriz, uma energia pioneira que sugere que você não apenas pode iniciar projetos ambiciosos, mas também tem a persistência e a visão necessárias para levá-los até a conclusão bem-sucedida. Esta impressão que você causa frequentemente resulta em outros naturalmente se voltarem para você em busca de direção, inspiração ou simplesmente para sentir a segurança que sua presença confiante proporciona. Sua aparência e maneira de se expressar comunicam originalidade, independência e uma recusa em se conformar com padrões que não ressoam com sua verdade interior. Na tradição cabalística, você carrega a vibração do número da harmonia, iniciação e autodomínio, sendo percebido como alguém que possui poder mental e austeridade natural."
    },
    2: {
      titulo: "Impressão 2 - A Aura Diplomática da Harmonia Personificada",
      texto: "Você projeta naturalmente uma aura de diplomacia, gentileza e harmonia que faz com que outros instintivamente se sintam à vontade em sua presença e busquem sua mediação em situações de conflito. Sua energia externa comunica receptividade, compreensão e uma capacidade inata de perceber e honrar as necessidades emocionais dos outros. Pessoas ao seu redor percebem em você uma força pacificadora, uma energia equilibradora que sugere que você possui a sabedoria e a sensibilidade necessárias para encontrar soluções que beneficiem a todos os envolvidos. Esta impressão que você causa frequentemente resulta em outros naturalmente confiarem em você seus segredos, preocupações e esperanças, pois sua presença transmite segurança emocional e compreensão genuína. Sua aparência e maneira de se expressar comunicam calma, organização e uma atenção cuidadosa aos detalhes que tornam a vida mais bela e harmoniosa. Na tradição cabalística, você carrega a vibração do intelecto superior e da concepção mental refinada, sendo percebido como alguém naturalmente bondoso, escrupuloso e confiável."
    },
    3: {
      titulo: "Impressão 3 - O Magnetismo Criativo da Alegria Contagiante",
      texto: "Você projeta naturalmente um magnetismo criativo e uma alegria contagiante que fazem com que outros instintivamente se sintam inspirados e elevados em sua presença. Sua energia externa comunica otimismo, criatividade e uma capacidade inata de encontrar beleza e possibilidades em qualquer situação. Pessoas ao seu redor percebem em você uma fonte de inspiração, uma energia vivificante que sugere que você possui o dom de transformar momentos comuns em experiências memoráveis e significativas. Esta impressão que você causa frequentemente resulta em outros naturalmente buscarem sua companhia quando precisam de encorajamento, criatividade ou simplesmente quando desejam experimentar a alegria de viver de forma mais plena. Sua aparência e maneira de se expressar comunicam expressividade, espontaneidade e uma capacidade natural de comunicar ideias e sentimentos de forma clara e envolvente. Você é percebido como alguém que possui o dom da palavra e a habilidade de inspirar outros através de sua expressão autêntica e criativa."
    },
    4: {
      titulo: "Impressão 4 - A Solidez Confiável da Estabilidade Personificada",
      texto: "Você projeta naturalmente uma impressão de solidez, confiabilidade e estabilidade que faz com que outros instintivamente o vejam como alguém em quem podem confiar completamente e com quem podem contar em qualquer circunstância. Sua energia externa comunica organização, disciplina e uma capacidade inata de transformar caos em ordem através de trabalho metódico e dedicação consistente. Pessoas ao seu redor percebem em você uma força estabilizadora, uma energia fundamentadora que sugere que você possui a paciência e a determinação necessárias para construir algo duradouro e significativo. Esta impressão que você causa frequentemente resulta em outros naturalmente buscarem sua orientação em questões práticas, sua ajuda em projetos que requerem organização sistemática, ou simplesmente sua presença quando precisam se sentir seguros e protegidos. Sua aparência e maneira de se expressar comunicam praticidade, responsabilidade e uma atenção meticulosa aos detalhes que garantem que tudo seja feito da maneira correta e no tempo apropriado."
    },
    5: {
      titulo: "Impressão 5 - A Energia Dinâmica da Liberdade em Movimento",
      texto: "Você projeta naturalmente uma energia dinâmica e uma aura de liberdade que fazem com que outros instintivamente o vejam como alguém aventureiro, versátil e cheio de possibilidades inexploradas. Sua energia externa comunica adaptabilidade, curiosidade e uma capacidade inata de encontrar oportunidades e soluções criativas em qualquer situação. Pessoas ao seu redor percebem em você uma força renovadora, uma energia expansiva que sugere que você possui a coragem e a flexibilidade necessárias para navegar através de mudanças e desafios com graça e otimismo. Esta impressão que você causa frequentemente resulta em outros naturalmente buscarem sua companhia quando desejam experimentar algo novo, sua perspectiva quando enfrentam situações que requerem pensamento inovador, ou simplesmente sua presença quando precisam de uma injeção de energia e entusiasmo. Sua aparência e maneira de se expressar comunicam espontaneidade, versatilidade e uma capacidade natural de se adaptar rapidamente a novas circunstâncias mantendo sempre uma atitude positiva e exploradora."
    },
    6: {
      titulo: "Impressão 6 - A Presença Nutritiva do Amor Incondicional",
      texto: "Você projeta naturalmente uma presença nutritiva e uma aura de amor incondicional que fazem com que outros instintivamente se sintam cuidados, valorizados e profundamente compreendidos em sua companhia. Sua energia externa comunica compaixão, responsabilidade e uma capacidade inata de criar ambientes onde todos se sentem seguros para serem autênticos e vulneráveis. Pessoas ao seu redor percebem em você uma força curativa, uma energia maternal/paternal que sugere que você possui a sabedoria e a dedicação necessárias para nutrir o crescimento e o bem-estar dos outros. Esta impressão que você causa frequentemente resulta em outros naturalmente buscarem seu conselho em questões do coração, sua presença quando precisam de conforto e apoio, ou simplesmente sua companhia quando desejam experimentar a sensação de serem verdadeiramente amados e aceitos. Sua aparência e maneira de se expressar comunicam calor humano, responsabilidade e uma atenção genuína ao bem-estar físico, emocional e espiritual daqueles que estão ao seu redor."
    },
    7: {
      titulo: "Impressão 7 - A Aura Misteriosa da Sabedoria Profunda",
      texto: "Você projeta naturalmente uma aura misteriosa e uma presença de sabedoria profunda que fazem com que outros instintivamente o vejam como alguém que possui conhecimentos e percepções que transcendem o comum. Sua energia externa comunica introspecção, intuição e uma capacidade inata de perceber verdades ocultas e padrões sutis que escapam à percepção ordinária. Pessoas ao seu redor percebem em você uma força contemplativa, uma energia investigativa que sugere que você possui a paciência e a profundidade necessárias para compreender os mistérios mais complexos da existência. Esta impressão que você causa frequentemente resulta em outros naturalmente buscarem sua perspectiva em questões filosóficas ou espirituais, sua orientação quando enfrentam dilemas que requerem reflexão profunda, ou simplesmente sua presença quando precisam de silêncio e contemplação. Sua aparência e maneira de se expressar comunicam serenidade, profundidade e uma qualidade atemporal que sugere conexão com dimensões mais elevadas da consciência."
    },
    8: {
      titulo: "Impressão 8 - A Autoridade Natural do Poder Equilibrado",
      texto: "Você projeta naturalmente uma autoridade natural e uma presença de poder equilibrado que fazem com que outros instintivamente o vejam como alguém capaz de liderar organizações, gerenciar recursos e tomar decisões importantes que afetam muitas pessoas. Sua energia externa comunica competência, ambição e uma capacidade inata de transformar visões em realidades concretas através de organização eficiente e determinação inabalável. Pessoas ao seu redor percebem em você uma força executiva, uma energia realizadora que sugere que você possui a visão e a capacidade de implementação necessárias para alcançar objetivos ambiciosos e criar mudanças significativas. Esta impressão que você causa frequentemente resulta em outros naturalmente buscarem sua liderança em projetos importantes, sua orientação em questões de negócios ou carreira, ou simplesmente sua presença quando precisam de inspiração para perseguir seus próprios objetivos materiais. Sua aparência e maneira de se expressar comunicam sucesso, determinação e uma capacidade natural de inspirar confiança e respeito através de suas realizações tangíveis."
    },
    9: {
      titulo: "Impressão 9 - A Presença Compassiva da Sabedoria Universal",
      texto: "Você projeta naturalmente uma presença compassiva e uma aura de sabedoria universal que fazem com que outros instintivamente o vejam como alguém que transcendeu limitações pessoais e dedica sua vida ao serviço de causas maiores. Sua energia externa comunica compreensão, generosidade e uma capacidade inata de ver além das diferenças superficiais para reconhecer a unidade fundamental que conecta todos os seres. Pessoas ao seu redor percebem em você uma força inspiradora, uma energia elevadora que sugere que você possui a compaixão e a sabedoria necessárias para ajudar outros a transcenderem suas próprias limitações e descobrirem seu potencial mais elevado. Esta impressão que você causa frequentemente resulta em outros naturalmente buscarem sua orientação em questões de crescimento espiritual, sua perspectiva quando enfrentam desafios que requerem uma visão mais ampla, ou simplesmente sua presença quando precisam se conectar com algo maior que eles mesmos. Sua aparência e maneira de se expressar comunicam universalidade, compaixão e uma qualidade atemporal que inspira outros a buscarem o melhor de si mesmos."
    }
  },

  expressao: {
    1: {
      titulo: "Expressão 1 - A Manifestação da Liderança Pioneira",
      texto: "Sua expressão natural no mundo se manifesta através de liderança pioneira, iniciativas inovadoras e a capacidade de abrir novos caminhos onde outros veem apenas obstáculos. Você se expressa melhor quando está na posição de comandar, criar e iniciar projetos que reflitam sua visão única e original. Sua forma de comunicação é direta, assertiva e inspiradora, capaz de motivar outros a seguirem sua liderança e abraçarem mudanças necessárias. Você possui um talento natural para identificar oportunidades antes que outros as percebam e tem a coragem de agir decisivamente mesmo em face da incerteza. Sua expressão criativa tende a ser inovadora e original, frequentemente estabelecendo novos padrões ou tendências em sua área de atuação. Você se destaca em situações que requerem iniciativa pessoal, tomada de decisão rápida e a capacidade de assumir responsabilidades significativas. Sua presença em grupos naturalmente eleva o nível de energia e motivação, pois você carrega dentro de si a chama da inspiração que acende o potencial de liderança nos outros."
    },
    2: {
      titulo: "Expressão 2 - A Arte da Diplomacia e Cooperação",
      texto: "Sua expressão natural no mundo se manifesta através da diplomacia refinada, da cooperação harmoniosa e da capacidade de criar pontes de entendimento entre pessoas e ideias aparentemente incompatíveis. Você se expressa melhor quando está facilitando colaborações, mediando conflitos e criando ambientes onde todos se sentem ouvidos e valorizados. Sua forma de comunicação é gentil, receptiva e profundamente empática, capaz de perceber nuances emocionais que outros frequentemente negligenciam. Você possui um talento natural para trabalhar em equipe, apoiar os esforços de outros e contribuir para o sucesso coletivo através de sua sensibilidade e atenção aos detalhes. Sua expressão criativa tende a ser colaborativa e harmoniosa, frequentemente envolvendo parcerias ou projetos que beneficiam múltiplas pessoas. Você se destaca em situações que requerem tato, paciência e a capacidade de encontrar soluções que satisfaçam as necessidades de todos os envolvidos. Sua presença em grupos naturalmente promove harmonia e cooperação, pois você possui o dom de fazer com que cada pessoa se sinta importante e valorizada."
    },
    3: {
      titulo: "Expressão 3 - A Comunicação Criativa e Inspiradora",
      texto: "Sua expressão natural no mundo se manifesta através da comunicação criativa, da expressão artística e da capacidade de inspirar alegria e otimismo em todos ao seu redor. Você se expressa melhor quando está compartilhando ideias, criando arte ou comunicando-se de forma que eleve o espírito e desperte a criatividade nos outros. Sua forma de comunicação é eloquente, expressiva e naturalmente cativante, capaz de transformar conceitos complexos em mensagens claras e inspiradoras. Você possui um talento natural para as artes, a escrita, a oratória e qualquer forma de expressão que permita que sua criatividade flua livremente. Sua expressão criativa tende a ser vibrante e original, frequentemente trazendo uma perspectiva única e refrescante para qualquer projeto ou situação. Você se destaca em situações que requerem criatividade, comunicação eficaz e a capacidade de inspirar e motivar outros através de sua expressão autêntica. Sua presença em grupos naturalmente eleva o humor e a energia criativa, pois você possui o dom de encontrar beleza e possibilidades em qualquer circunstância."
    },
    4: {
      titulo: "Expressão 4 - A Construção Metódica e Duradoura",
      texto: "Sua expressão natural no mundo se manifesta através da construção metódica, da organização sistemática e da capacidade de transformar visões em realidades concretas através de trabalho disciplinado e persistente. Você se expressa melhor quando está construindo, organizando e estabelecendo sistemas que funcionem de forma eficiente e confiável ao longo do tempo. Sua forma de comunicação é clara, prática e fundamentada em fatos, capaz de transmitir informações complexas de maneira organizada e compreensível. Você possui um talento natural para o planejamento, a administração e a implementação de projetos que requerem atenção meticulosa aos detalhes e execução consistente. Sua expressão criativa tende a ser prática e funcional, frequentemente resultando em criações que são tanto belas quanto úteis. Você se destaca em situações que requerem organização, disciplina e a capacidade de manter o foco em objetivos de longo prazo mesmo quando enfrentando obstáculos. Sua presença em grupos naturalmente promove ordem e eficiência, pois você possui o dom de criar estruturas que permitem que outros trabalhem de forma mais produtiva e organizada."
    },
    5: {
      titulo: "Expressão 5 - A Versatilidade Dinâmica e Adaptável",
      texto: "Sua expressão natural no mundo se manifesta através da versatilidade dinâmica, da adaptabilidade criativa e da capacidade de prosperar em ambientes de mudança constante e diversidade. Você se expressa melhor quando está explorando novas possibilidades, experimentando diferentes abordagens e mantendo múltiplas opções abertas simultaneamente. Sua forma de comunicação é animada, versátil e naturalmente persuasiva, capaz de se adaptar ao seu público e transmitir entusiasmo por novas ideias e experiências. Você possui um talento natural para vendas, marketing, viagens e qualquer atividade que envolva interação com pessoas diversas e situações variadas. Sua expressão criativa tende a ser experimental e inovadora, frequentemente combinando elementos de diferentes áreas para criar algo completamente novo e inesperado. Você se destaca em situações que requerem flexibilidade, criatividade e a capacidade de pensar rapidamente e adaptar-se a circunstâncias em mudança. Sua presença em grupos naturalmente introduz energia renovadora e perspectivas frescas, pois você possui o dom de ver oportunidades onde outros veem apenas desafios."
    },
    6: {
      titulo: "Expressão 6 - O Serviço Amoroso e a Criação de Harmonia",
      texto: "Sua expressão natural no mundo se manifesta através do serviço amoroso, da criação de harmonia e da capacidade de nutrir o crescimento e o bem-estar de outros através de cuidado dedicado e responsabilidade compassiva. Você se expressa melhor quando está cuidando, ensinando, curando ou criando ambientes onde outros podem florescer e desenvolver seu potencial máximo. Sua forma de comunicação é calorosa, compreensiva e naturalmente curativa, capaz de oferecer conforto e orientação mesmo nas situações mais desafiadoras. Você possui um talento natural para educação, cura, aconselhamento e qualquer atividade que envolva o cuidado direto com o bem-estar de outros. Sua expressão criativa tende a ser bela e harmoniosa, frequentemente focada em criar ambientes que promovam paz, beleza e bem-estar. Você se destaca em situações que requerem compaixão, responsabilidade e a capacidade de colocar as necessidades dos outros antes das suas próprias. Sua presença em grupos naturalmente promove harmonia e cuidado mútuo, pois você possui o dom de fazer com que todos se sintam amados, valorizados e apoiados."
    },
    7: {
      titulo: "Expressão 7 - A Investigação Profunda e a Sabedoria Contemplativa",
      texto: "Sua expressão natural no mundo se manifesta através da investigação profunda, da análise contemplativa e da capacidade de descobrir verdades ocultas através de estudo meticuloso e reflexão silenciosa. Você se expressa melhor quando está pesquisando, analisando, meditando ou explorando os aspectos mais profundos e misteriosos da existência. Sua forma de comunicação é reflexiva, profunda e frequentemente reveladora, capaz de oferecer insights únicos que iluminam aspectos da realidade que outros não percebem. Você possui um talento natural para pesquisa, análise, ensino espiritual e qualquer atividade que envolva a busca por conhecimento profundo e compreensão espiritual. Sua expressão criativa tende a ser profunda e significativa, frequentemente explorando temas filosóficos, espirituais ou psicológicos. Você se destaca em situações que requerem paciência, introspecção e a capacidade de trabalhar independentemente em projetos que demandam concentração prolongada. Sua presença em grupos naturalmente eleva o nível de consciência e reflexão, pois você possui o dom de fazer perguntas que levam outros a questionarem suas suposições e explorarem dimensões mais profundas de si mesmos."
    },
    8: {
      titulo: "Expressão 8 - A Liderança Executiva e a Manifestação Material",
      texto: "Sua expressão natural no mundo se manifesta através da liderança executiva, da organização em grande escala e da capacidade de transformar recursos em resultados tangíveis e mensuráveis. Você se expressa melhor quando está dirigindo organizações, gerenciando projetos ambiciosos e exercendo autoridade de forma a criar mudanças significativas no mundo material. Sua forma de comunicação é autoritativa, persuasiva e naturalmente inspiradora, capaz de motivar grandes grupos de pessoas a trabalharem juntas em direção a objetivos ambiciosos. Você possui um talento natural para negócios, administração, política e qualquer atividade que envolva a coordenação de recursos e pessoas em grande escala. Sua expressão criativa tende a ser grandiosa e impactante, frequentemente resultando em criações que influenciam muitas pessoas e deixam um legado duradouro. Você se destaca em situações que requerem visão estratégica, capacidade de organização e a habilidade de tomar decisões importantes sob pressão. Sua presença em grupos naturalmente eleva o nível de ambição e realização, pois você possui o dom de inspirar outros a pensarem grande e trabalharem duro para alcançar objetivos significativos."
    },
    9: {
      titulo: "Expressão 9 - A Compaixão Universal e o Serviço Humanitário",
      texto: "Sua expressão natural no mundo se manifesta através da compaixão universal, do serviço humanitário e da capacidade de inspirar outros a transcenderem limitações pessoais em favor do bem maior da humanidade. Você se expressa melhor quando está servindo causas que beneficiam muitas pessoas, promovendo compreensão entre culturas diferentes e trabalhando para aliviar o sofrimento mundial. Sua forma de comunicação é inspiradora, universal e profundamente tocante, capaz de despertar o melhor nas pessoas e motivá-las a contribuir para um mundo melhor. Você possui um talento natural para trabalho humanitário, ensino espiritual, arte universal e qualquer atividade que promova a evolução da consciência humana. Sua expressão criativa tende a ser universal e atemporal, frequentemente abordando temas que ressoam com pessoas de todas as culturas e backgrounds. Você se destaca em situações que requerem visão ampla, compaixão genuína e a capacidade de inspirar outros a se dedicarem ao serviço desinteressado. Sua presença em grupos naturalmente eleva o nível de consciência e compaixão, pois você possui o dom de ajudar outros a verem além de suas preocupações pessoais e se conectarem com propósitos maiores."
    }
  },

  destino: {
    1: {
      titulo: "Destino 1 - O Caminho da Liderança e Independência",
      texto: "Seu destino está intrinsecamente ligado ao desenvolvimento da liderança pioneira e à capacidade de iniciar novos ciclos de crescimento e inovação. Você veio a esta vida para aprender a ser independente, original e corajoso, abrindo caminhos que outros poderão seguir. Sua jornada de vida o levará através de experiências que desenvolverão sua capacidade de tomar decisões importantes, assumir responsabilidades significativas e liderar outros através de seu exemplo pessoal. Você está destinado a ser um pioneiro em sua área de atuação, estabelecendo novos padrões e criando oportunidades onde antes não existiam. Seu caminho envolve aprender a equilibrar a necessidade de independência com a responsabilidade de usar sua liderança para o bem de outros. Você enfrentará desafios que testarão sua coragem, determinação e capacidade de manter sua integridade mesmo quando enfrentando oposição. Através dessas experiências, você desenvolverá a força interior e a confiança necessárias para cumprir seu destino como líder e inovador. Sua vida será marcada por momentos de iniciação onde você será chamado a dar passos corajosos em direção ao desconhecido, confiando em sua visão interior e em sua capacidade de criar algo novo e valioso."
    },
    2: {
      titulo: "Destino 2 - O Caminho da Cooperação e Harmonia",
      texto: "Seu destino está intrinsecamente ligado ao desenvolvimento da diplomacia refinada e à capacidade de criar harmonia e cooperação entre pessoas e grupos diversos. Você veio a esta vida para aprender a ser um mediador, um pacificador e um facilitador de relacionamentos harmoniosos. Sua jornada de vida o levará através de experiências que desenvolverão sua sensibilidade emocional, sua capacidade de compreender diferentes perspectivas e sua habilidade de encontrar soluções que beneficiem a todos os envolvidos. Você está destinado a ser uma força de equilíbrio e harmonia em um mundo frequentemente dividido por conflitos e mal-entendidos. Seu caminho envolve aprender a usar sua sensibilidade como uma força, não como uma vulnerabilidade, e a desenvolver a paciência necessária para trabalhar com outros de forma colaborativa. Você enfrentará desafios que testarão sua capacidade de manter a paz interior mesmo em meio a conflitos externos, e de encontrar formas criativas de unir pessoas que parecem irreconciliáveis. Através dessas experiências, você desenvolverá a sabedoria emocional e a compaixão necessárias para cumprir seu destino como construtor de pontes e criador de harmonia."
    },
    3: {
      titulo: "Destino 3 - O Caminho da Expressão Criativa e Comunicação",
      texto: "Seu destino está intrinsecamente ligado ao desenvolvimento da expressão criativa e à capacidade de comunicar ideias e sentimentos de forma que inspire e eleve outros. Você veio a esta vida para aprender a usar sua criatividade como uma força transformadora, trazendo beleza, alegria e inspiração para o mundo. Sua jornada de vida o levará através de experiências que desenvolverão seus talentos artísticos, sua capacidade de comunicação e sua habilidade de encontrar formas únicas de expressar sua visão interior. Você está destinado a ser um comunicador, um artista ou um inspirador que usa sua expressão criativa para tocar a vida de outros de forma significativa. Seu caminho envolve aprender a equilibrar a necessidade de expressão pessoal com a responsabilidade de usar seus talentos para elevar e inspirar outros. Você enfrentará desafios que testarão sua capacidade de manter sua autenticidade criativa mesmo quando enfrentando críticas ou rejeição, e de encontrar formas de transformar experiências difíceis em expressões belas e significativas. Através dessas experiências, você desenvolverá a confiança criativa e a habilidade comunicativa necessárias para cumprir seu destino como portador de beleza e inspiração."
    },
    4: {
      titulo: "Destino 4 - O Caminho da Construção e Estabilidade",
      texto: "Seu destino está intrinsecamente ligado ao desenvolvimento da capacidade de construir bases sólidas e duradouras que possam sustentar o crescimento e a prosperidade de muitas pessoas. Você veio a esta vida para aprender a ser um construtor, um organizador e um criador de sistemas que funcionem de forma eficiente e confiável. Sua jornada de vida o levará através de experiências que desenvolverão sua disciplina, sua paciência e sua capacidade de trabalhar de forma metódica e consistente em direção a objetivos de longo prazo. Você está destinado a ser uma força estabilizadora em um mundo frequentemente caótico, criando ordem e estrutura onde antes havia confusão. Seu caminho envolve aprender a equilibrar a necessidade de segurança e estabilidade com a flexibilidade necessária para se adaptar a mudanças inevitáveis. Você enfrentará desafios que testarão sua perseverança, sua capacidade de manter o foco mesmo quando o progresso parece lento, e sua habilidade de encontrar satisfação no trabalho árduo bem executado. Através dessas experiências, você desenvolverá a força de caráter e a competência prática necessárias para cumprir seu destino como construtor de fundações sólidas."
    },
    5: {
      titulo: "Destino 5 - O Caminho da Liberdade e Experiência",
      texto: "Seu destino está intrinsecamente ligado ao desenvolvimento da versatilidade e à capacidade de prosperar em ambientes de mudança constante e diversidade. Você veio a esta vida para aprender a ser um explorador, um aventureiro e um adaptador que abraça a mudança como uma oportunidade de crescimento. Sua jornada de vida o levará através de experiências diversas que desenvolverão sua flexibilidade, sua curiosidade e sua capacidade de encontrar oportunidades em qualquer situação. Você está destinado a ser uma força de renovação e progresso, trazendo novas ideias e perspectivas para situações estagnadas. Seu caminho envolve aprender a equilibrar a necessidade de liberdade e variedade com a responsabilidade de usar suas experiências para beneficiar outros. Você enfrentará desafios que testarão sua capacidade de se adaptar rapidamente a mudanças inesperadas, de manter sua identidade mesmo quando experimentando diferentes papéis, e de encontrar estabilidade interior em meio à mudança externa constante. Através dessas experiências, você desenvolverá a sabedoria prática e a adaptabilidade necessárias para cumprir seu destino como agente de mudança e renovação."
    },
    6: {
      titulo: "Destino 6 - O Caminho do Serviço e Responsabilidade",
      texto: "Seu destino está intrinsecamente ligado ao desenvolvimento da capacidade de nutrir, cuidar e servir ao bem-estar de outros através de amor incondicional e responsabilidade compassiva. Você veio a esta vida para aprender a ser um curador, um professor e um cuidador que dedica sua vida ao crescimento e bem-estar de outros. Sua jornada de vida o levará através de experiências que desenvolverão sua compaixão, sua capacidade de sacrifício e sua habilidade de criar ambientes onde outros podem florescer. Você está destinado a ser uma força curativa em um mundo frequentemente ferido, oferecendo amor, compreensão e apoio prático para aqueles que precisam. Seu caminho envolve aprender a equilibrar a necessidade de cuidar dos outros com a importância de cuidar de si mesmo, evitando o martírio desnecessário. Você enfrentará desafios que testarão sua capacidade de amar incondicionalmente mesmo quando não é correspondido, de manter limites saudáveis enquanto serve aos outros, e de encontrar alegria no serviço desinteressado. Através dessas experiências, você desenvolverá a sabedoria do coração e a força compassiva necessárias para cumprir seu destino como curador e nutrir de almas."
    },
    7: {
      titulo: "Destino 7 - O Caminho da Busca Espiritual e Sabedoria",
      texto: "Seu destino está intrinsecamente ligado ao desenvolvimento da sabedoria espiritual e à capacidade de compreender os mistérios mais profundos da existência. Você veio a esta vida para aprender a ser um buscador da verdade, um investigador dos mistérios e um ponte entre o mundo material e as dimensões espirituais. Sua jornada de vida o levará através de experiências que desenvolverão sua intuição, sua capacidade de análise profunda e sua habilidade de perceber padrões ocultos que conectam todas as coisas. Você está destinado a ser uma fonte de sabedoria e compreensão espiritual, oferecendo insights que ajudam outros a compreenderem o significado mais profundo de suas experiências. Seu caminho envolve aprender a equilibrar a necessidade de solitude e contemplação com a responsabilidade de compartilhar sua sabedoria com aqueles que estão prontos para recebê-la. Você enfrentará desafios que testarão sua fé, sua capacidade de confiar em sua intuição mesmo quando ela contradiz a lógica convencional, e sua habilidade de manter sua conexão espiritual em um mundo frequentemente materialista. Através dessas experiências, você desenvolverá a percepção espiritual e a sabedoria contemplativa necessárias para cumprir seu destino como guia espiritual e guardião da sabedoria ancestral."
    },
    8: {
      titulo: "Destino 8 - O Caminho do Poder Material e Autoridade",
      texto: "Seu destino está intrinsecamente ligado ao desenvolvimento da capacidade de exercer poder e autoridade de forma sábia e responsável, criando abundância material que beneficie muitas pessoas. Você veio a esta vida para aprender a ser um líder executivo, um organizador em grande escala e um construtor de impérios que deixam um legado duradouro. Sua jornada de vida o levará através de experiências que desenvolverão sua capacidade de organização, sua visão estratégica e sua habilidade de transformar recursos em resultados tangíveis e mensuráveis. Você está destinado a ser uma força de realização material e progresso econômico, criando oportunidades e prosperidade para muitas pessoas. Seu caminho envolve aprender a equilibrar a busca por sucesso material com a responsabilidade espiritual de usar seu poder para o bem maior. Você enfrentará desafios que testarão sua integridade, sua capacidade de manter seus valores mesmo quando enfrentando pressões para comprometer seus princípios, e sua habilidade de usar seu sucesso para elevar outros ao invés de apenas beneficiar a si mesmo. Através dessas experiências, você desenvolverá a sabedoria executiva e a autoridade moral necessárias para cumprir seu destino como líder responsável e criador de abundância."
    },
    9: {
      titulo: "Destino 9 - O Caminho da Compaixão Universal e Serviço Humanitário",
      texto: "Seu destino está intrinsecamente ligado ao desenvolvimento da compaixão universal e à capacidade de servir à evolução da consciência humana através de amor incondicional e sabedoria espiritual. Você veio a esta vida para aprender a ser um servidor da humanidade, um professor espiritual e um exemplo vivo de amor universal. Sua jornada de vida o levará através de experiências que desenvolverão sua compreensão da natureza humana, sua capacidade de perdoar e sua habilidade de ver a unidade subjacente que conecta todos os seres. Você está destinado a ser uma força de elevação espiritual e transformação social, inspirando outros a transcenderem suas limitações pessoais em favor do bem maior. Seu caminho envolve aprender a equilibrar o amor universal com o discernimento prático, oferecendo compaixão sem se tornar um mártir desnecessário. Você enfrentará desafios que testarão sua capacidade de amar incondicionalmente mesmo aqueles que o ferem, de manter sua fé na bondade humana mesmo quando confrontado com crueldade, e de encontrar formas práticas de expressar sua compaixão de maneira que realmente beneficie outros. Através dessas experiências, você desenvolverá a sabedoria universal e a compaixão ilimitada necessárias para cumprir seu destino como servidor da evolução humana e portador da luz divina."
    }
  }
};

// Exportar para uso global
if (typeof window !== 'undefined') {
  window.interpretacoesPitagoricasCompletas = interpretacoesPitagoricasCompletas;
}
