// Sinastria Numerológica Completa - Todas as 81 combinações
// Baseado em: La Sinastría Numerológica, Os Números e o Amor, e outras fontes fornecidas

const sinastria_completa = {
  "1-4": {
    titulo: "União 1-4 - Visão Pioneira e Construção Sólida",
    texto: "Esta combinação representa uma sinastria de complementaridade poderosa que une a energia visionária e iniciadora do número 1 com a capacidade organizacional e construtiva do número 4, criando uma parceria que pode transformar sonhos ambiciosos em realidades concretas e duradouras. O parceiro 1 oferece visão, inspiração e a coragem de iniciar projetos ambiciosos, enquanto o parceiro 4 fornece a estrutura, a disciplina e a persistência necessárias para transformar essas visões em conquistas tangíveis. Esta é uma união onde a criatividade encontra a praticidade, onde a inspiração encontra a implementação, resultando em uma parceria que pode construir impérios duradouros tanto no âmbito pessoal quanto profissional. O parceiro 4 frequentemente se sente energizado e motivado pela confiança e visão do parceiro 1, encontrando propósito e direção para suas habilidades organizacionais, enquanto o parceiro 1 se beneficia enormemente da estabilidade, da confiabilidade e da capacidade de execução meticulosa do parceiro 4. Juntos, eles podem alcançar objetivos que requerem tanto inspiração quanto transpiração, combinando a faísca da iniciativa com a força da perseverança. Os desafios desta combinação surgem quando o parceiro 1 se torna impaciente com o ritmo mais cauteloso e metódico do parceiro 4, ou quando o parceiro 4 se sente sobrecarregado pelas mudanças constantes de direção ou pela impaciência do parceiro 1. A chave para o sucesso reside no reconhecimento mútuo de que ambos os estilos são essenciais para o sucesso a longo prazo, na comunicação clara sobre expectativas e cronogramas, e na criação de um equilíbrio entre inovação e estabilidade."
  },
  "1-5": {
    titulo: "União 1-5 - Liderança Dinâmica e Liberdade Criativa",
    texto: "Esta combinação cria uma sinastria excepcionalmente dinâmica e estimulante que une a força diretiva e determinada do número 1 com a versatilidade aventureira e a sede de liberdade do número 5, resultando em uma parceria que pode ser tanto emocionantemente produtiva quanto desafiantemente imprevisível. O parceiro 1 traz liderança, foco e a capacidade de transformar oportunidades em realizações concretas, enquanto o parceiro 5 oferece adaptabilidade, criatividade e uma perspectiva constantemente renovada que mantém a relação fresca e cheia de possibilidades. Esta é uma união onde a determinação encontra a flexibilidade, onde a consistência encontra a variedade, criando uma dinâmica que pode resultar em aventuras extraordinárias e conquistas inovadoras. O parceiro 5 frequentemente se sente inspirado e direcionado pela clareza de propósito e confiança do parceiro 1, encontrando canais produtivos para sua energia expansiva, enquanto o parceiro 1 se beneficia da perspectiva ampla, da adaptabilidade e da capacidade de encontrar oportunidades inesperadas do parceiro 5. Juntos, eles podem explorar territórios desconhecidos tanto literal quanto figurativamente, combinando a coragem de liderar com a sabedoria de se adaptar. Os desafios desta combinação incluem a possível frustração do parceiro 1 com a aparente falta de foco ou compromisso do parceiro 5, e a sensação do parceiro 5 de estar sendo restringido ou controlado pela necessidade de direção consistente do parceiro 1. O sucesso desta união requer flexibilidade mútua, comunicação aberta sobre necessidades de liberdade versus estabilidade, e a criação de projetos que honrem tanto a necessidade de liderança quanto a necessidade de exploração."
  },
  "1-6": {
    titulo: "União 1-6 - Liderança Responsável e Amor Nutritivo",
    texto: "Esta combinação representa uma das sinastrias mais equilibradas e mutuamente enriquecedoras da numerologia, unindo a energia assertiva e visionária do número 1 com a natureza compassiva e nutritiva do número 6, criando uma parceria que combina ambição pessoal com responsabilidade social e amor incondicional. O parceiro 1 oferece direção, motivação e a capacidade de alcançar objetivos ambiciosos, enquanto o parceiro 6 fornece apoio emocional, estabilidade doméstica e a sabedoria do coração que mantém todas as conquistas em perspectiva humana. Esta é uma união onde a realização pessoal encontra o serviço amoroso, onde o sucesso individual é sempre temperado pela consideração pelo bem-estar de outros, especialmente da família e da comunidade próxima. O parceiro 6 frequentemente se sente inspirado e protegido pela força e determinação do parceiro 1, encontrando segurança para expressar plenamente sua natureza nutritiva, enquanto o parceiro 1 se beneficia profundamente do amor incondicional, da sabedoria emocional e da capacidade de criar um lar harmonioso do parceiro 6. Juntos, eles podem construir não apenas sucessos materiais, mas também um legado de amor, cuidado e responsabilidade social que beneficia gerações futuras. Os desafios desta combinação podem surgir quando o parceiro 1 se torna excessivamente focado em objetivos externos, negligenciando as necessidades emocionais e domésticas, ou quando o parceiro 6 se torna excessivamente protetor ou controlador, limitando a liberdade de ação necessária para o parceiro 1. A chave para o sucesso reside no equilíbrio entre ambição e amor, no reconhecimento de que tanto a realização quanto o relacionamento são essenciais para uma vida plena, e na criação de objetivos compartilhados que honrem tanto a necessidade de conquista quanto a necessidade de conexão emocional profunda."
  },
  "1-7": {
    titulo: "União 1-7 - Ação Inspirada e Sabedoria Contemplativa",
    texto: "Esta combinação cria uma sinastria fascinante e potencialmente transformadora que une a energia extrovertida e ativa do número 1 com a natureza introspectiva e espiritualmente orientada do número 7, resultando em uma parceria que pode integrar ação inspirada com sabedoria profunda. O parceiro 1 traz iniciativa, confiança e a capacidade de manifestar ideias no mundo material, enquanto o parceiro 7 oferece profundidade, intuição e uma perspectiva espiritual que pode elevar qualquer empreendimento além do meramente material. Esta é uma união onde a ação encontra a contemplação, onde a manifestação externa encontra a compreensão interior, criando possibilidades para realizações que são tanto materialmente bem-sucedidas quanto espiritualmente significativas. O parceiro 7 frequentemente se sente energizado e direcionado pela confiança e capacidade de ação do parceiro 1, encontrando canais práticos para suas insights espirituais, enquanto o parceiro 1 se beneficia da profundidade, da sabedoria e da perspectiva mais ampla oferecida pelo parceiro 7. Juntos, eles podem criar projetos que não apenas alcançam sucesso mundano, mas também contribuem para a evolução da consciência e o bem-estar espiritual. Os desafios desta combinação incluem a possível impaciência do parceiro 1 com a necessidade de introspecção e análise cuidadosa do parceiro 7, e a possível frustração do parceiro 7 com o que pode perceber como superficialidade ou pressa excessiva do parceiro 1. O sucesso desta união requer respeito mútuo pelos diferentes ritmos e necessidades, comunicação paciente sobre perspectivas diferentes, e a criação de espaços onde tanto a ação quanto a contemplação são valorizadas e integradas harmoniosamente."
  },
  "1-8": {
    titulo: "União 1-8 - Dupla Liderança e Poder Compartilhado",
    texto: "Esta combinação representa uma das sinastrias mais poderosas e potencialmente desafiadoras da numerologia, unindo duas energias naturalmente dominantes e ambiciosas que podem tanto criar impérios extraordinários quanto entrar em conflitos épicos pelo controle e reconhecimento. Ambos os parceiros possuem forte necessidade de liderança, sucesso material e reconhecimento público, criando uma dinâmica que pode ser tanto mutuamente inspiradora quanto competitivamente destrutiva. O parceiro 1 oferece visão pioneira, iniciativa e a coragem de abrir novos caminhos, enquanto o parceiro 8 traz capacidade organizacional em grande escala, visão estratégica e a habilidade de construir estruturas duradouras de poder e influência. Quando esta combinação funciona harmoniosamente, o resultado pode ser uma parceria que conquista objetivos extraordinários, constrói legados duradouros e exerce influência significativa em suas áreas de atuação. Ambos se beneficiam da energia ambiciosa do outro, encontrando na parceria um catalisador poderoso para suas aspirações individuais e compartilhadas. No entanto, os desafios são igualmente significativos: ambos podem lutar pelo controle, ter dificuldade em comprometer-se ou ceder, e podem inadvertidamente competir ao invés de colaborar. A tendência de ambos a serem dominantes pode criar conflitos constantes sobre direção, métodos e reconhecimento. O sucesso desta união requer maturidade emocional excepcional, definição clara de áreas de responsabilidade e autoridade, e um compromisso consciente de usar o poder combinado para objetivos que transcendem egos individuais. Quando conseguem trabalhar juntos, representam uma força quase imparável para a realização de objetivos ambiciosos."
  },
  "1-9": {
    titulo: "União 1-9 - Liderança Visionária e Compaixão Universal",
    texto: "Esta combinação cria uma sinastria profundamente significativa que une a energia pioneira e assertiva do número 1 com a sabedoria compassiva e a orientação humanitária do número 9, resultando em uma parceria que pode liderar mudanças positivas significativas no mundo. O parceiro 1 oferece a força motriz, a confiança e a capacidade de iniciar movimentos e projetos, enquanto o parceiro 9 traz perspectiva universal, compaixão profunda e a sabedoria que vem da compreensão da natureza humana em todas as suas manifestações. Esta é uma união onde a liderança pessoal encontra o serviço universal, onde a ambição individual é elevada por propósitos que transcendem interesses pessoais. O parceiro 9 frequentemente se sente inspirado e direcionado pela energia e confiança do parceiro 1, encontrando canais práticos para sua compaixão e desejo de servir, enquanto o parceiro 1 se beneficia da sabedoria, da perspectiva ampla e da profundidade emocional do parceiro 9. Juntos, eles podem liderar causas humanitárias, criar organizações que beneficiam muitas pessoas, ou simplesmente viver suas vidas de forma que inspire outros a serem melhores versões de si mesmos. Os desafios desta combinação podem incluir a possível frustração do parceiro 1 com o que pode perceber como idealismo excessivo ou falta de foco prático do parceiro 9, e a possível preocupação do parceiro 9 com o que pode ver como egoísmo ou falta de consideração pelos outros por parte do parceiro 1. O sucesso desta união requer equilíbrio entre ambição pessoal e responsabilidade social, comunicação aberta sobre valores e prioridades, e a criação de objetivos que honrem tanto a necessidade de realização individual quanto o desejo de contribuir para o bem maior da humanidade."
  },
  "2-3": {
    titulo: "União 2-3 - Harmonia Diplomática e Expressão Criativa",
    texto: "Esta combinação representa uma das sinastrias mais naturalmente harmoniosas e mutuamente inspiradoras da numerologia, unindo a sensibilidade diplomática e a natureza cooperativa do número 2 com a criatividade expressiva e o otimismo contagiante do número 3, criando uma parceria que floresce através da beleza, da comunicação e da celebração compartilhada da vida. O parceiro 2 oferece apoio emocional, sensibilidade às necessidades do outro e a capacidade de criar harmonia em todos os aspectos da relação, enquanto o parceiro 3 traz inspiração criativa, alegria de viver e a habilidade de transformar momentos comuns em experiências memoráveis e significativas. Esta é uma união onde a diplomacia encontra a arte, onde a cooperação encontra a expressão, resultando em uma parceria que pode criar beleza tanto em sua vida privada quanto em suas contribuições para o mundo. O parceiro 3 frequentemente se sente apoiado e compreendido pelo parceiro 2, encontrando um público apreciativo e encorajador para sua expressão criativa, enquanto o parceiro 2 se beneficia da alegria, do otimismo e da capacidade de encontrar beleza em qualquer situação oferecida pelo parceiro 3. Juntos, eles podem criar um lar cheio de beleza e harmonia, desenvolver projetos artísticos colaborativos, ou simplesmente viver suas vidas de forma que inspire outros através de seu exemplo de amor e criatividade. Os desafios desta combinação são geralmente menores, mas podem incluir a tendência do parceiro 2 a ser excessivamente sensível a críticas sobre a expressão criativa do parceiro 3, ou a possível frustração do parceiro 3 com o que pode perceber como falta de iniciativa ou energia do parceiro 2. O sucesso desta união é quase natural, requerendo principalmente comunicação aberta sobre necessidades criativas e emocionais, e a manutenção de um equilíbrio entre apoio mútuo e expressão individual."
  },
  "2-4": {
    titulo: "União 2-4 - Cooperação Harmoniosa e Construção Estável",
    texto: "Esta combinação cria uma sinastria excepcionalmente estável e mutuamente apoiadora que une a natureza diplomática e cooperativa do número 2 com a capacidade organizacional e construtiva do número 4, resultando em uma parceria que pode construir bases sólidas para uma vida compartilhada próspera e harmoniosa. O parceiro 2 oferece sensibilidade emocional, capacidade de mediação e a habilidade de criar atmosferas de paz e cooperação, enquanto o parceiro 4 fornece estrutura, disciplina e a capacidade de transformar sonhos compartilhados em realidades concretas através de trabalho consistente e planejamento cuidadoso. Esta é uma união onde a harmonia encontra a estabilidade, onde a cooperação encontra a construção, criando uma base sólida para crescimento mútuo e realização compartilhada. O parceiro 4 frequentemente se sente apoiado e compreendido pelo parceiro 2, encontrando motivação emocional para seus esforços construtivos, enquanto o parceiro 2 se beneficia da segurança, da confiabilidade e da capacidade de criar estruturas duradouras oferecida pelo parceiro 4. Juntos, eles podem construir não apenas sucessos materiais, mas também um relacionamento que serve como modelo de estabilidade e harmonia para outros. Esta combinação é particularmente forte para construir famílias, estabelecer negócios duradouros, ou criar qualquer tipo de estrutura que requer tanto cooperação quanto persistência. Os desafios podem incluir a tendência de ambos a evitar conflitos necessários, resultando em problemas não resolvidos, ou a possível estagnação quando ambos se tornam excessivamente confortáveis com rotinas estabelecidas. O sucesso desta união requer comunicação aberta sobre necessidades e expectativas, disposição para abordar problemas diretamente quando necessário, e a manutenção de um equilíbrio entre estabilidade e crescimento."
  },
  "2-5": {
    titulo: "União 2-5 - Diplomacia Estável e Aventura Dinâmica",
    texto: "Esta combinação representa uma sinastria de contrastes complementares que une a natureza estável e cooperativa do número 2 com a energia dinâmica e aventureira do número 5, criando uma parceria que pode equilibrar segurança emocional com crescimento através de novas experiências. O parceiro 2 oferece estabilidade emocional, apoio incondicional e a capacidade de criar um porto seguro para onde o parceiro 5 pode sempre retornar, enquanto o parceiro 5 traz variedade, aventura e perspectivas constantemente renovadas que mantêm a relação fresca e em crescimento. Esta é uma união onde a segurança encontra a aventura, onde a estabilidade encontra a mudança, criando uma dinâmica que pode resultar em crescimento mútuo significativo. O parceiro 5 frequentemente se sente apoiado e aceito pelo parceiro 2, encontrando a segurança emocional necessária para explorar com confiança, enquanto o parceiro 2 se beneficia da energia renovadora, das novas perspectivas e das experiências enriquecedoras trazidas pelo parceiro 5. Juntos, eles podem criar uma vida que combina a segurança de um relacionamento estável com a emoção de descobertas constantes. Os desafios desta combinação incluem a possível ansiedade do parceiro 2 com a necessidade de mudança e aventura do parceiro 5, e a possível frustração do parceiro 5 com o que pode perceber como resistência à mudança ou necessidade excessiva de segurança do parceiro 2. O sucesso desta união requer comunicação aberta sobre necessidades de segurança versus aventura, criação de compromissos que honrem ambas as necessidades, e o desenvolvimento de confiança mútua que permite tanto estabilidade quanto crescimento através de novas experiências."
  },
  "2-6": {
    titulo: "União 2-6 - Harmonia Dupla e Amor Multiplicado",
    texto: "Esta combinação cria uma das sinastrias mais naturalmente harmoniosas e mutuamente nutritivas da numerologia, unindo duas naturezas que compartilham valores fundamentais de amor, cuidado, harmonia e responsabilidade pelos outros. Ambos os parceiros possuem uma orientação natural para o serviço, a cooperação e a criação de ambientes onde outros podem florescer, resultando em uma parceria que pode ser profundamente curativa e transformadora tanto para eles quanto para todos ao seu redor. O parceiro 2 oferece diplomacia, sensibilidade emocional e a capacidade de mediar e harmonizar, enquanto o parceiro 6 traz amor incondicional, responsabilidade compassiva e a habilidade de nutrir e cuidar. Esta é uma união onde o amor encontra a harmonia, onde o cuidado encontra a cooperação, criando uma atmosfera de paz e bem-estar que pode servir como santuário para ambos os parceiros e suas famílias. Ambos se beneficiam da natureza amorosa e apoiadora do outro, encontrando na parceria uma fonte constante de compreensão, aceitação e encorajamento. Juntos, eles podem criar lares excepcionalmente harmoniosos, trabalhar efetivamente em causas humanitárias, ou simplesmente viver suas vidas de forma que demonstre o poder transformador do amor incondicional. Os desafios desta combinação podem incluir uma tendência a evitar conflitos necessários, resultando em ressentimentos não expressos, ou a possibilidade de ambos se tornarem excessivamente focados no cuidado com outros, negligenciando suas próprias necessidades. O sucesso desta união requer equilíbrio entre dar e receber, comunicação honesta sobre necessidades pessoais, e a manutenção de limites saudáveis que permitam cuidar de outros sem se esgotar."
  },
  "2-7": {
    titulo: "União 2-7 - Sensibilidade Emocional e Profundidade Espiritual",
    texto: "Esta combinação representa uma sinastria de profundidade emocional e espiritual excepcional que une a sensibilidade diplomática e a natureza cooperativa do número 2 com a sabedoria contemplativa e a orientação espiritual do número 7, criando uma parceria que pode explorar as dimensões mais profundas da experiência humana. O parceiro 2 oferece apoio emocional, compreensão intuitiva e a capacidade de criar um ambiente seguro para vulnerabilidade e crescimento, enquanto o parceiro 7 traz profundidade filosófica, insight espiritual e a habilidade de perceber significados ocultos em todas as experiências. Esta é uma união onde a sensibilidade encontra a sabedoria, onde a cooperação encontra a contemplação, resultando em uma parceria que pode ser profundamente transformadora para ambos os parceiros. O parceiro 7 frequentemente se sente compreendido e apoiado pelo parceiro 2, encontrando um companheiro que aprecia sua profundidade e não tenta forçá-lo a ser mais extrovertido, enquanto o parceiro 2 se beneficia da sabedoria, da perspectiva espiritual e da capacidade de encontrar significado profundo em experiências compartilhadas oferecida pelo parceiro 7. Juntos, eles podem desenvolver uma compreensão profunda da natureza humana, explorar práticas espirituais, ou simplesmente criar um relacionamento que serve como um espaço sagrado de crescimento mútuo. Os desafios desta combinação podem incluir a tendência de ambos a serem excessivamente sensíveis ou introspectivos, resultando em isolamento social, ou a possível dificuldade em lidar com aspectos mais práticos da vida. O sucesso desta união requer equilíbrio entre profundidade e praticidade, comunicação aberta sobre necessidades espirituais e emocionais, e a criação de conexões com o mundo exterior que honrem sua natureza contemplativa."
  },
  "2-8": {
    titulo: "União 2-8 - Apoio Diplomático e Poder Executivo",
    texto: "Esta combinação cria uma sinastria de complementaridade poderosa que une a natureza apoiadora e diplomática do número 2 com a energia executiva e ambiciosa do número 8, resultando em uma parceria que pode alcançar sucessos significativos através da combinação de sensibilidade emocional com capacidade organizacional. O parceiro 2 oferece apoio emocional, habilidades diplomáticas e a capacidade de criar harmonia em relacionamentos importantes, enquanto o parceiro 8 traz visão estratégica, capacidade de liderança e a habilidade de transformar objetivos em realizações concretas. Esta é uma união onde o apoio encontra a ambição, onde a diplomacia encontra o poder, criando uma dinâmica que pode resultar em sucessos tanto pessoais quanto profissionais. O parceiro 8 frequentemente se beneficia enormemente do apoio emocional, da sabedoria relacional e da capacidade de mediação do parceiro 2, encontrando um parceiro que pode ajudar a navegar as complexidades dos relacionamentos humanos, enquanto o parceiro 2 se sente inspirado e protegido pela força, determinação e capacidade de realização do parceiro 8. Juntos, eles podem construir organizações bem-sucedidas, alcançar posições de influência, ou simplesmente criar uma vida próspera que combina sucesso material com harmonia relacional. Os desafios desta combinação podem incluir a possível negligência das necessidades emocionais do parceiro 2 quando o parceiro 8 se torna excessivamente focado em objetivos materiais, ou a possível frustração do parceiro 8 com o que pode perceber como falta de ambição ou iniciativa do parceiro 2. O sucesso desta união requer equilíbrio entre ambição e relacionamento, reconhecimento mútuo das diferentes contribuições, e comunicação clara sobre expectativas e necessidades."
  },
  "2-9": {
    titulo: "União 2-9 - Cooperação Harmoniosa e Compaixão Universal",
    texto: "Esta combinação representa uma das sinastrias mais espiritualmente elevadas e mutuamente enriquecedoras da numerologia, unindo a natureza cooperativa e sensível do número 2 com a sabedoria compassiva e a orientação humanitária do número 9, criando uma parceria que pode servir como um exemplo vivo de amor incondicional e serviço desinteressado. O parceiro 2 oferece apoio emocional, capacidade de cooperação e a habilidade de criar harmonia em todos os relacionamentos, enquanto o parceiro 9 traz perspectiva universal, compaixão profunda e a sabedoria que vem da compreensão da interconexão de todos os seres. Esta é uma união onde a cooperação encontra a compaixão, onde a sensibilidade encontra a sabedoria, resultando em uma parceria que pode contribuir significativamente para a cura e elevação da consciência humana. O parceiro 9 frequentemente se sente apoiado e compreendido pelo parceiro 2, encontrando um companheiro que compartilha seus valores de amor e serviço, enquanto o parceiro 2 se beneficia da sabedoria, da perspectiva ampla e da capacidade de ver além das limitações pessoais oferecida pelo parceiro 9. Juntos, eles podem trabalhar em causas humanitárias, criar organizações de serviço, ou simplesmente viver suas vidas de forma que inspire outros através de seu exemplo de amor incondicional. Os desafios desta combinação são geralmente menores, mas podem incluir a tendência de ambos a se sacrificarem excessivamente pelos outros, negligenciando suas próprias necessidades, ou a possível dificuldade em estabelecer limites saudáveis. O sucesso desta união requer equilíbrio entre serviço aos outros e autocuidado, comunicação aberta sobre necessidades pessoais, e a manutenção de uma perspectiva que honre tanto o amor universal quanto o amor pessoal."
  }
};

// Adicionar ao objeto principal
Object.assign(interpretacoesSinastria, sinastria_completa);

// Exportar para uso global
if (typeof window !== 'undefined') {
  window.interpretacoesSinastria = Object.assign(window.interpretacoesSinastria || {}, sinastria_completa);
}
